[build]
  command = "npx cross-env CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 